"""Build restore manifest from migration inventory."""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def build_manifest(inventory_dir: Path, tool_root: Path | None = None) -> dict:
    inventory_dir = inventory_dir.expanduser().resolve()
    tool_root = (tool_root or Path(__file__).resolve().parents[1]).resolve()

    env = load_json(inventory_dir / "environment-snapshot.json")
    vscode = load_json(inventory_dir / "vscode-extensions.json")
    homebrew = load_json(inventory_dir / "homebrew-inventory.json")
    quick_actions = load_json(inventory_dir / "quick-actions-inventory.json")
    audio = load_json(inventory_dir / "audio-devices-inventory.json")
    brewfile = inventory_dir / "Brewfile"

    aliases = env.get("aliases") or {}
    alias_count = aliases.get("count", 0)
    shell_lines = env.get("shell_config_lines") or {}
    shell_init_count = sum(len(v) for v in shell_lines.values())

    vscode_count = sum(
        len(ed.get("extensions") or [])
        for ed in vscode.get("editors") or []
    )
    brew_formula_count = homebrew.get("formula_count", 0)
    brew_cask_count = homebrew.get("cask_count", 0)
    qa_count = quick_actions.get("workflow_count", 0) + quick_actions.get("shortcuts_count", 0)
    audio_count = audio.get("device_count", 0)

    restore_cmd = f"{tool_root / 'mac-migration'} restore"
    components: list[dict] = []

    if alias_count:
        components.append(
            {
                "id": "aliases",
                "label": "Shell aliases",
                "count": alias_count,
                "source": "environment-snapshot.json",
                "restore": f"{restore_cmd} aliases --inventory-dir {inventory_dir}",
            }
        )
    if shell_init_count or env.get("homebrew", {}).get("shellenv_lines"):
        components.append(
            {
                "id": "shell",
                "label": "Shell init (pyenv, brew, nvm)",
                "count": shell_init_count,
                "source": "environment-snapshot.json",
                "restore": f"{restore_cmd} shell --inventory-dir {inventory_dir}",
            }
        )
    if brewfile.exists() and (brew_formula_count or brew_cask_count):
        components.append(
            {
                "id": "homebrew",
                "label": "Homebrew packages",
                "count": brew_formula_count + brew_cask_count,
                "source": "Brewfile",
                "restore": f"{restore_cmd} homebrew --inventory-dir {inventory_dir}",
            }
        )
    if vscode_count:
        components.append(
            {
                "id": "vscode",
                "label": "VS Code / Cursor extensions",
                "count": vscode_count,
                "source": "vscode-extensions.json",
                "restore": f"{restore_cmd} vscode --inventory-dir {inventory_dir}",
            }
        )
    if qa_count:
        components.append(
            {
                "id": "quick-actions",
                "label": "Quick Actions (Automator + Shortcuts)",
                "count": qa_count,
                "source": "quick-actions-inventory.json",
                "restore": f"{restore_cmd} quick-actions --inventory-dir {inventory_dir}",
            }
        )
    if audio_count:
        components.append(
            {
                "id": "audio",
                "label": "Audio devices (BlackHole, virtual drivers)",
                "count": audio_count,
                "source": "audio-devices-inventory.json",
                "restore": f"{restore_cmd} audio --inventory-dir {inventory_dir}",
            }
        )

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "inventory_dir": str(inventory_dir),
        "tool_root": str(tool_root),
        "restore_command": f"{restore_cmd} all --inventory-dir {inventory_dir}",
        "components": components,
    }


def render_wrapper_script(manifest: dict) -> str:
    inventory_dir = manifest["inventory_dir"]
    tool_root = manifest["tool_root"]
    return f"""#!/usr/bin/env bash
# Auto-generated by mac-migration collect — run on the new Mac.
set -euo pipefail
TOOL_ROOT="${{MAC_MIGRATION_ROOT:-{tool_root}}}"
exec "$TOOL_ROOT/mac-migration" restore all --inventory-dir "{inventory_dir}"
"""


def write_manifest(inventory_dir: Path, tool_root: Path | None = None) -> Path:
    inventory_dir = inventory_dir.expanduser().resolve()
    manifest = build_manifest(inventory_dir, tool_root)
    out_path = inventory_dir / "restore-manifest.json"
    out_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    wrapper = inventory_dir / "restore.sh"
    wrapper.write_text(render_wrapper_script(manifest), encoding="utf-8")
    wrapper.chmod(0o755)
    return out_path


def main() -> None:
    inventory_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "migration-inventory"
    tool_root = Path(sys.argv[2]) if len(sys.argv) > 2 else None
    out_path = write_manifest(inventory_dir, tool_root)
    manifest = load_json(out_path)
    print(f"==> Restore manifest: {out_path}")
    print(f"==> One-step on new Mac: bash {inventory_dir / 'restore.sh'}")
    for comp in manifest.get("components") or []:
        print(f"    - {comp['id']}: {comp.get('count', 0)} item(s)")


if __name__ == "__main__":
    main()
